INSERT INTO USER (id, NAME, EMAIL)VALUES (1, 'Stacy', 'stacy@gmail.com');
INSERT INTO USER (id, NAME, EMAIL)VALUES (2,'Raman', 'raman@gmail.com');
INSERT INTO USER (id, NAME, EMAIL)VALUES (3, 'Alex', 'alex@gmail.com');
INSERT INTO USER (id, NAME, EMAIL)VALUES (4, 'Volga', 'volga@gmail.com');

INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID)VALUES (100.0, 1);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID)VALUES (90.0, 2);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID)VALUES (80.0, 3);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID)VALUES (60.0, 4);
